# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Rust formatting and linting
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        name: cargo fmt
        description: Format Rust code with rustfmt
        entry: cargo fmt --manifest-path vault-audit-tools/Cargo.toml --
        language: system
        files: \.rs$
        pass_filenames: true
      - id: clippy
        name: cargo clippy
        description: Lint Rust code with clippy
        entry: bash -c 'cd vault-audit-tools && cargo clippy --all-targets --all-features -- -D warnings'
        language: system
        files: \.rs$
        pass_filenames: false

  # Secrets detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (?x)^(
            \.env\.example|
            README\.md|
            \.githooks/.*|
            scripts/.*|
            run\.sh|
            run_in_venv\.sh|
            setup_venv\.sh
          )$

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
