# cargo-deny configuration
# https://embarkstudios.github.io/cargo-deny/

[advisories]
version = 2

[licenses]
version = 2
allow = ["MIT", "Apache-2.0", "Apache-2.0 WITH LLVM-exception", "BSD-2-Clause", "BSD-3-Clause", "ISC", "CDLA-Permissive-2.0", "Unicode-3.0"]

[bans]
multiple-versions = "warn"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
