name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  snyk-deps:
    runs-on: ubuntu-latest
    # don’t try to use repo secrets on forked PRs
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Ensure lockfile (Snyk needs Cargo.lock)
        working-directory: vault-audit-tools
        run: cargo generate-lockfile

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Run Snyk to check for vulnerabilities
        working-directory: vault-audit-tools
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --severity-threshold=high --sarif-file-output=snyk.sarif

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: vault-audit-tools/snyk.sarif

      - name: Monitor dependencies with Snyk
        working-directory: vault-audit-tools
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk monitor --project-name=vault-audit-tools
